#!/bin/bash
# Script 5: Open Source Manifesto Generator (VLC)
# Author: Vaibhavi Ugam Shet Govekar

echo "Answer three questions to generate your manifesto."
echo ""

read -p "1. Name one open-source tool you use every day (e.g., VLC): " TOOL
read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM
read -p "3. Name one thing you would build and share freely: " BUILD

DATE=$(date '+%d %B %Y')
OUTPUT="manifesto_$(whoami).txt"

# Alias example (concept demonstration only)
# Example: alias ll='ls -la'

# Compose the manifesto and save it
echo "Open Source Manifesto — $DATE" > $OUTPUT
echo "" >> $OUTPUT
echo "I believe in the power of open-source software." >> $OUTPUT
echo "Tools like $TOOL (such as VLC Media Player) show how collaboration and transparency can build better technology." >> $OUTPUT
echo "To me, freedom means $FREEDOM, and I hope to contribute to this community by building $BUILD and sharing it with the world." >> $OUTPUT
echo "" >> $OUTPUT
echo "— Generated by $(whoami)" >> $OUTPUT

echo ""
echo "Manifesto saved to $OUTPUT"
echo ""
cat $OUTPUT